### ISSUE TITLE
Decorator triggers exception when receiving a request from a source other than Discord.

### ISSUE THREAD

**Issue by creallfluharty** [discord/discord-interactions-python#2]
### Description
Currently, if the method wrapped by the `verify_key_decorator` decorator receives a request that doesn't contain either of the `X-Signature-*` headers, or a body without the `type` key, it will result in an exception that will trigger a 500 error. This isn't particularly problematic given that requests from any source other than Discord should be rejected anyway, but it would be preferable to respond with a 403 error instead so that these errors are not included in the logs of the application.

### Steps to reproduce
1. Handle slash commands with something like the code included in the project's [current README][1]:
```python
@verify_key_decorator(CLIENT_PUBLIC_KEY)
def interactions():
  if request.json['type'] == InteractionType.APPLICATION_COMMAND:
    return jsonify({
        'type': InteractionResponseType.CHANNEL_MESSAGE_WITH_SOURCE,
        'data': {
            'content': 'Hello world'
        }
    })
```
2. Manually make a request to the bot's interactions endpoint (Using for example a web browser).
3. Observe that a 500 error is produced.

### Additional Details
In the case of the missing headers, the exception may look something like this (Though the traceback probably won't include the google cloud stuff):

```python
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 66, in view_func
    return function(request._get_current_object())
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/discord_interactions/__init__.py", line 44, in __decorator
    if not verify_key(request.data, signature, timestamp, client_public_key):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/discord_interactions/__init__.py", line 24, in verify_key
    message = timestamp.encode() + raw_body
AttributeError: 'NoneType' object has no attribute 'encode'
```

The `NoneType` in this case is the `None` returned by `request.headers.get('X-Signature-Timestamp')` since that header is not present in the request.

[1]: https://github.com/discord/discord-interactions-python/blob/fd03078df1c1f53c68302ac26c054c4174499529/README.md

**Comment by typpo** [comment]
Thanks for the fix, this has been released in v0.1.2
